# celery_worker.dockerfile
FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

# Start Celery
CMD ["celery", "-A", "app.tasks.celery", "worker", "--loglevel=info"]
